packages:
  - 'apps/*'
allowBuilds:
  '@firebase/util': true
  '@prisma/client': true
  '@prisma/engines': true
  '@scarf/scarf': true
  canvas: set this to true or false
  esbuild: true
  prisma: true
  protobufjs: true
