import { prisma } from '$lib/db';
import { normalizeExecutionMode } from './execution-modes';
import { classifyEmergencyType } from '$lib/server/emergency-templates';

/**
 * Populate the `emergency_type` param for ACT-A2P-004. Prefers the AI-provided
 * `aiEmergencyType` (T2.1); otherwise classifies via the shared template library
 * (T2.2) so it can't drift from the customer-facing emergency copy.
 */
function resolveEmergencyType(enrichment: any, event: any): string {
	if (enrichment?.aiEmergencyType) return enrichment.aiEmergencyType;
	const text = [enrichment?.aiSummary, enrichment?.aiServiceMentioned, event?.unstructuredText, event?.reviewText]
		.filter(Boolean)
		.join(' ');
	return classifyEmergencyType(text);
}

export class ActionQueueLog {
	decision_id: string;
	steps: { status: string; message: string; timestamp: string; description?: string }[] = [];

	constructor(decision_id: string) {
		this.decision_id = decision_id;
	}

	step(status: string, message: string, description?: string) {
		const timestamp = new Date().toISOString().replace('T', ' ').replace('Z', '');
		const statusIcon = status.includes('error') ? '🔴' : (status.includes('blocked') || status.includes('warning')) ? '🟡' : '🔵';
		console.log(`${statusIcon} [${timestamp}] Section 4 - ${status.toUpperCase()} : ${message}`);
		if (description) {
			console.log(`      → ${description}`);
		}
		this.steps.push({ status, message, timestamp, description });
	}
}

export class ActionQueueEngine {
	static async processToQueue(decisionId: string) {
		const log = new ActionQueueLog(decisionId);
		log.step('started', `Processing Decision ${decisionId} to Action Queue`, "Initialization of the Parameter Resolution engine. We are taking the strategic decision and preparing the individual work orders.");

		// 1. Fetch Decision Data
		const decision = await prisma.pipelineDecision.findUnique({
			where: { decisionId },
			include: { 
				event: { include: { enrichments: true, customerProfile: true } },
				actionQueue: true // To check for existing records
			}
		});

		if (!decision) {
			log.step('error', `Decision not found: ${decisionId}`);
			throw new Error(`Decision not found: ${decisionId}`);
		}

		// 2. Duplicate Prevention Check
		if (decision.actionQueue.length > 0) {
			log.step('warning', `Action Queue records already exist for decision ${decisionId}. Skipping re-processing.`, "Guard triggered to prevent duplicate work orders for the same decision.");
			return { queueItems: decision.actionQueue, log };
		}

		const companyId = decision.event.companyId;
		if (!companyId) {
			log.step('error', `Company ID missing from event: ${decision.event.id}`);
			throw new Error(`Company ID missing from event: ${decision.event.id}`);
		}

		// 3. Deduplicate Selected Actions (Safety Net)
		const selectedActionIds = [...new Set(decision.selectedActionIds as string[])];
		log.step('actions_received', `Received ${selectedActionIds.length} unique action(s) from Orchestrator`, `The dispatcher has taken the deduplicated list of tasks generated by the Brain.`);

		const queueItems = [];

		// 4. Resolve Actions and Blocked Audit Records
		const allActionIds = [...selectedActionIds];
		const blockedAuditIds = (decision.blockedActionIds as any[]) || [];

		// Combine for a complete audit trace in the queue
		for (const actionId of allActionIds) {
			const actionMeta = await prisma.pipelineActionLibrary.findUnique({ where: { actionId } });
			if (!actionMeta) {
				log.step('warning', `Action ${actionId} not found in library`);
				continue;
			}

			const lane = await this.determineLane(actionMeta, companyId, log);
			const requiredParams = (actionMeta.requiredParams as string[]) || [];
			const resolvedParams = await this.resolveParameters(requiredParams, decision, companyId, log);
			
			// Map Correct Status
			const status = lane === 'approval_required' ? 'pending_approval' : 'ready_for_execution';
			
			// Calculate SLA (12-hour window for approval tasks)
			const dueAt = lane === 'approval_required' ? new Date(Date.now() + 12 * 60 * 60 * 1000) : null;

			const qtraceId = `qtrace_${Math.random().toString(36).substring(2, 14)}`;

			const queueItem = await prisma.pipelineActionQueue.create({
				data: {
					queueTraceId: qtraceId,
					decisionId: decision.id,
					actionId: actionId,
					executionLane: lane,
					parameters: resolvedParams,
					status: status,
					dueAt: dueAt,
					consultantId: decision.consultantId,
					consultantReviewRequired: decision.consultantReviewRequired,
					approvalRoute: decision.approvalRoute
				}
			});

			queueItems.push(queueItem);
			log.step('item_queued', `🎯 Queued: ${actionId} | Status: ${status.toUpperCase()} | Lane: [${lane.toUpperCase()}]`, `Action ${actionId} is successfully stored with trace ID ${qtraceId}.`);
		}

		// 5. Create Blocked Audit Records
		for (const blocked of blockedAuditIds) {
			const qtraceId = `qtrace_blocked_${Math.random().toString(36).substring(2, 10)}`;
			const blockedItem = await prisma.pipelineActionQueue.create({
				data: {
					queueTraceId: qtraceId,
					decisionId: decision.id,
					actionId: blocked.id,
					executionLane: 'blocked',
					status: 'blocked_audit',
					parameters: { block_reason: blocked.reason },
					consultantId: decision.consultantId
				}
			});
			queueItems.push(blockedItem);
			log.step('blocked_audit', `Logged Blocked Action: ${blocked.id}`, `Preserved audit record for safety violation: ${blocked.reason}`);
		}

		log.step('completed', `Successfully processed ${queueItems.length} total queue/audit records`, "All strategic tasks have been turned into detailed work orders or blocked audit logs.");
		return { queueItems, log };
	}

	private static async determineLane(actionMeta: any, companyId: string, log: ActionQueueLog): Promise<string> {
		if (actionMeta.isPublicFacing) {
			log.step('lane_assignment', `Action ${actionMeta.actionId} is public-facing. Forced to APPROVAL_REQUIRED per Safety Rule ORC-004.`, "Even if high automation was requested, the system has locked this public task into the Approval Lane for safety.");
			return 'approval_required';
		}

		const clientProfile = await prisma.pipelineOrchestratorProfile.findUnique({ where: { companyId } });
		if (clientProfile?.automationLevel === 'aggressive') {
			log.step('lane_assignment', `Action ${actionMeta.actionId} set to AUTOMATIC via Aggressive automation profile.`, "This internal task will execute instantly based on the client's aggressive automation settings.");
			return 'automatic';
		}

		if (clientProfile?.automationLevel === 'conservative') {
			log.step('lane_assignment', `Action ${actionMeta.actionId} set to APPROVAL_REQUIRED via Conservative automation profile.`, "The client's conservative profile requires a human check even for internal tasks.");
			return 'approval_required';
		}

		const lane = normalizeExecutionMode(actionMeta.defaultExecutionMode);
		log.step('lane_assignment', `Action ${actionMeta.actionId} using default lane: ${lane.toUpperCase()}`, `Applying the standard default lane for ${actionMeta.actionId}.`);
		return lane;
	}

	private static async resolveParameters(requiredParams: string[], decision: any, companyId: string, log: ActionQueueLog): Promise<Record<string, any>> {
		const params: Record<string, any> = {};
		const event = decision.event;
		const businessConfig = await prisma.pipelineBusinessConfig.findUnique({ where: { companyId } });
		const enrichment = event.enrichments?.[0] || {};

		for (const key of requiredParams) {
			switch (key) {
				case 'customer_name': 
					params[key] = event.authorName || enrichment?.aiCustomerName || event.customerProfile?.displayName || 'Valued Customer'; 
					break;
				case 'rating': params[key] = event.reviewRatingNumeric; break;
				case 'platform': params[key] = event.provider === 'google_business_profile' ? 'Google' : event.provider; break;
				case 'provider': params[key] = event.provider; break;
				case 'event_type': params[key] = event.eventType; break;
				case 'brand_tone': params[key] = businessConfig?.brandTone || 'professional'; break;
				case 'office_hours': params[key] = businessConfig?.officeTimezone || 'UTC'; break;
				case 'review_text': params[key] = event.reviewText || event.unstructuredText; break;
				case 'text_content': params[key] = event.unstructuredText; break;
				case 'ai_summary': params[key] = enrichment.aiSummary; break;
				case 'sentiment': params[key] = enrichment.aiSentiment; break;
				case 'intent': params[key] = enrichment.aiRequestedAction || 'Unknown'; break;
				case 'phone_number': params[key] = event.customerProfile?.phoneNumber || 'Unknown'; break;
				case 'urgency_level':
					// Map deterministic priority to urgency level
					if (decision.priority <= 1) params[key] = 'high';
					else if (decision.priority === 2) params[key] = 'medium';
					else params[key] = 'low';
					break;
				case 'emergency_type':
					// Required by ACT-A2P-004 (emergency dispatch). Prefer an explicit
					// AI-provided type once T2.1 adds `aiEmergencyType` to the schema;
					// until then, derive a coarse category from the message text so the
					// dispatch alert carries a meaningful type instead of null.
					params[key] = resolveEmergencyType(enrichment, event);
					break;
				case 'complaint_topics':
					params[key] = enrichment.aiComplaintTopics ? (typeof enrichment.aiComplaintTopics === 'string' ? JSON.parse(enrichment.aiComplaintTopics) : enrichment.aiComplaintTopics) : [];
					break;
				default: params[key] = null;
			}
			log.step('param_resolved', `Resolved {${key}} -> ${params[key]}`, `Extracted the specific ${key} data point from the event context.`);
		}
		return params;
	}
}
